### ISSUE TITLE
EODC Scene Search Script: sat_api_client error when running in QGIS

### ISSUE THREAD

**Issue by redfrexx** [GlobWetlandAfricaIII/GWA_scripts#20]
I've added the python script for the S2 scene search to the processing toolbox on the EODC VM. It's located in Scripts/Sentinel Tools/Sentinel-2 Scene Search in the processing Toolbox. But I got two issues:

Issue 1:
I wasn't able to install the package on the EODC VM, because of permission issues. Any idea why it won't work? 

![python_error_sat_api](https://user-images.githubusercontent.com/5021557/36251453-873b0262-1241-11e8-8e84-2e96814620d3.JPG)

Issue 2:
On my computer installing sat_api_client for the QGIS python worked without any problems and if I run the S2 search script outside of QGIS but within an anaconda environment the S2 scene query works fine. But when I run it in QGIS I get this error message. 

```
> 
> Traceback (most recent call last):
>   File "C:\OSGEO4~1\apps\Python27\lib\logging\__init__.py", line 875, in emit
>     self.flush()
>   File "C:\OSGEO4~1\apps\Python27\lib\logging\__init__.py", line 835, in flush
>     self.stream.flush()
> IOError: [Errno 9] Bad file descriptor
> Logged from file connectionpool.py, line 818
```

Any idea what the problem might be?

**Comment by j08lue** [comment]
Regarding issue 1: 
Did you try `pip install https://github.com/DHI-GRAS/sat-api-client/archive/master.zip` **in OSGeo shell**? Only there are `PYTHONPATH` and perhaps other environment variables set correctly. 

Also, make sure you have `python-dateutil` and `requests` installed through the OSGeo4W installer. The GWA install should include those already.

Regarding issue 2:
Is this actually an exception that gets raised, or only a warning? This is `logging` failing because QGIS' Python does not have a `STDOUT` stream.  See https://stackoverflow.com/questions/4230855/why-am-i-getting-ioerror-9-bad-file-descriptor-error-while-making-print-st/35941587

You might be able fix this by setting `sys.stdout = None` somewhere in the beginning of your script:
```python
import sys
if sys.executable.endswith("pythonw.exe"):
    sys.stdout = sys.stdout = None
```

**Comment by j08lue** [comment]
Or, better, use this recipe:

https://github.com/DHI-GRAS/QGIS_redirect_stdout

**Comment by j08lue** [comment]
> Regarding issue 2:
> Is this actually an exception that gets raised, or only a warning?

I tested it. It is only a warning. `snappy` is imported fine.

**Comment by redfrexx** [comment]
Installing sat_api_client worked now. But the other problem remains. After including the redirect_stdout() I'm getting a different error message:
![error_msg_ssl](https://user-images.githubusercontent.com/5021557/36368880-8aaba710-1559-11e8-9acc-34341f832957.JPG)

**Comment by redfrexx** [comment]
It works using sentinelsat. I'll just leave it like that for now and we'll change the password after the workshop. ;)

**Comment by j08lue** [comment]
I guess you fixed the `No module named redirect_stdout`, right? That was just about adding that module to your `sys.path` or including the code.

I don't know why you are seeing the `SSLError`. Could be that SSL is not properly configured in QGIS Python. But I guess SciHub is using SSL, too... Puzzling.

**Comment by j08lue** [comment]
Fine with your solution using `sentinelsat`. I guess we can close this for now. Feel free to open another issue if you are going back to `sat-api-client` and experience more problems.
