### ISSUE TITLE
WCR workflow: SAR water detection

### ISSUE THREAD

**Issue by redfrexx** [GlobWetlandAfricaIII/GWA_scripts#21]
When running step 6 of the WCR workflow the following error occurs:

![wcr_step6_error01](https://user-images.githubusercontent.com/5021557/36256348-d3638554-1252-11e8-993b-a8d903dc9ab4.JPG)
![wcr_step6_error02](https://user-images.githubusercontent.com/5021557/36256349-d38d1252-1252-11e8-961c-f9a7e028ddea.JPG)

**Comment by redfrexx** [comment]
sorry dubplicate 
-> https://github.com/GlobWetlandAfrica/GWA_installer/issues/10

**Comment by j08lue** [comment]
~~This is not a duplicate, but it might actually be linked to the `snappy` installation.~~

But the message from the logs that you are showing is probably again just a warnings because of the `sys.stdout` problem you also encountered in https://github.com/GlobWetlandAfrica/GWA_scripts/issues/20.

The real problem is this `The specified module could not be found`, which is Windows messing up. I'll look into it.

**Comment by j08lue** [comment]
Stale. Let's revisit this if someone else encounters this issue.
